# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'EasyMapping', '~> 0.6'
pod 'INTULocationManager', '~> 1.2'